deltaspike/examples/data-examples/src/main/java/org/apache/deltaspike/example/ArticleController.java
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.deltaspike.example;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.transaction.Transactional;

@Named
@ViewScoped
@Transactional
public class ArticleController implements Serializable
{

    private Article article = new Article();

    @Inject
    private Logger log;

    @Inject
    private ArticleRepository articleRepository;
    
    @Inject
    private FacesContext facesContext;
    
    @HttpParam("aid") 
    @Inject
    private String aid; // article id

    public Article getArticle()
    {
        return article;
    }

    public void setArticle(Article article)
    {
        this.article = article;
    }

    public Article findArticleById(Long id)
    {
        article = articleRepository.findBy(id);
        return article;
    }

    
    public String persist()
    {
        article.setDate(new Date());
        articleRepository.save(this.article);
        facesContext.addMessage(null, new FacesMessage("article:" + article.getTitle() + " persisted"));
        return "persisted";
    }

    public String delete(Article article)
    {
        articleRepository.remove(article);
        facesContext.addMessage(null, new FacesMessage("article:" + article.getTitle() + " deleted"));
        return "deleted";
    }

    public List<Article> getAllArticles()
    {
        return articleRepository.findAll();
    }
    
    public void loadArticle() 
    {
        if (aid != null)
        {
            this.article = findArticleById(Long.valueOf(aid));
        }
    }
    
}

deltaspike/examples/data-examples/src/main/webapp/add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
-->
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <f:metadata>
        <f:viewAction action="#{articleController.loadArticle}"/>
    </f:metadata>

    <h:head>
        <title>Simple JPA  page</title>
    </h:head>

    <h:body>
        <h1>#{empty(articleController.article.id) ? 'Add New ' : 'Edit '}Article</h1>
        <h:form>
            <h:panelGrid columns="2">
                <h:outputLabel value="title:" for="title"/>
                <h:inputText id="title" value="#{articleController.article.title}" size="20"/>

                <h:outputLabel value="content:" for="content"/>
                <h:inputTextarea id="content" value="#{articleController.article.content}" cols="20" rows="5"/>

                <h:commandButton value="#{empty(articleController.article.id) ? 'Add New ' : 'Edit '}Article" 
                                 action="#{articleController.persist}"/>
            </h:panelGrid>
        </h:form>

    </h:body>

</html>

deltaspike/examples/data-examples/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
-->
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>Simple Data Module page</title>
    </h:head>

    <h:body>
        <h1>Deltaspike Data module examples</h1>
        <h:link value=">>Add new article" outcome="add.xhtml" />
        <br />
        <h:link value=">>article list" outcome="list.xhtml" />
        <br />
    </h:body>

</html>

deltaspike/examples/data-examples/src/main/webapp/list.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
-->
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>Simple JPA  page</title>
    </h:head>

    <h:body>
        <h1>Article List</h1>
        <h:messages style="color:red"/>

        <h:form>
            <h:dataTable value="#{articleController.allArticles}" var="article" border="1">
                <h:column>
                    <f:facet name="header">ID</f:facet>
                    <h:outputText value="#{article.id}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">title</f:facet>
                    <h:outputText value="#{article.title}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">date</f:facet>
                    <h:outputText value="#{article.date}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">operation</f:facet>
                    <h:link value="edit" outcome="add.xhtml">
                        <f:param name="aid" value="#{article.id}"/>
                    </h:link>
                    #{' '}
                    <h:commandLink value="delete" action="#{articleController.delete(article)}"/>
                </h:column>
            </h:dataTable>
        </h:form>

        <h:link value=">>add new article" outcome="add.xhtml"/>
    </h:body>

</html>